### ISSUE TITLE
IMX names

### ISSUE THREAD

**Issue by ponsfrilus** [epfl-sti/wordpress.theme#114]
Changes requested by @dalgetty:
Materials Science -> Materials Science and Engineering
Génie des matériaux -> Science et génie des matériaux

**Comment by ponsfrilus** [comment]
![ckibfpanhelncokg](https://user-images.githubusercontent.com/176002/48333797-f82cdb80-e658-11e8-9bff-9fea3bb5bef2.png)
![aecgbdkmhdoojied](https://user-images.githubusercontent.com/176002/48333784-f19e6400-e658-11e8-8c4a-f984b04ba98f.png)

Please validate the line break for both french and english.

**Comment by dalgetty** [comment]
yes, go ahead

thanks in advance



Sent from my Samsung Galaxy smartphone.


-------- Original message --------
