### ISSUE TITLE
"Dean-office" différentes versions EN / FR

### ISSUE THREAD

**Issue by alexwiderski** [epfl-sti/wordpress.theme#126]
Est-ce que cela a déjà été décidé? Quelle version est correcte?

**Comment by ponsfrilus** [comment]
Does someone fixed that  @alexwiderski ? I can see any differences.

**Comment by alexwiderski** [comment]
@ponsfrilus une version avec 6 personnes et autre avec 10. Pour ne pas être différent, j'ai mis les 4 autres qui manquaient. Mais nous avons besoin de quelqu'un pour confirmer si c'est correct

**Comment by ponsfrilus** [comment]
@alexwiderski je pense que c'est ok, MG nous avait demandé d'ajouter des personnes, on a du oublier de le faire en FR. Je ferme cette issue, à réouvrir si j'ai tort.
