### ISSUE TITLE
Latest everything on homepage must be actual data

### ISSUE THREAD

**Issue by domq** [epfl-sti/wordpress.theme#19]

**Comment by ponsfrilus** [comment]
e.g. for the slider: we should use posts in a specific category with featured image as input data for the slider. Perhaps plugin like [Soliloquy](https://soliloquywp.com/how-to-add-a-featured-image-slider-in-wordpress/) or [similar](https://wordpress.org/plugins/search/featured-image-slider/) can do the job.
