### ISSUE TITLE
Right menu fixes

### ISSUE THREAD

**Issue by ponsfrilus** [epfl-sti/wordpress.theme#22]
![image](https://user-images.githubusercontent.com/176002/34316152-654a01f8-e78f-11e7-8136-cba5d0b83b53.png)

* Find a smart way to handle long text;
* Test sub-levels of menus;
* Highlight current item.

**Comment by ponsfrilus** [comment]
Is that one c3b191ed3298782200b72d1cf0fb1a959b2679c1 fixes it ?

**Comment by domq** [comment]
Definitely @ponsfrilus ☺
