### ISSUE TITLE
Fix resizing

### ISSUE THREAD

**Issue by ponsfrilus** [epfl-sti/wordpress.theme#23]
![screenshot_2017-12-23_03-17-59](https://user-images.githubusercontent.com/176002/34316194-10b97168-e790-11e7-9226-b7d4fd319d80.png)

The latest menu dive in the page when the width is around 1150px

**Comment by domq** [comment]
Mostly fixed at or around cd3cf83ddc91d804f266c56462386475dbe1e0e7
