### ISSUE TITLE
Translate "School of Engineering" header text in french

### ISSUE THREAD

**Issue by ponsfrilus** [epfl-sti/wordpress.theme#32]
The text "School of Engineering" next to the EPFL logo should be translated in french pages.

Proposals: 
1. Factulté **Sciences et Techniques de l'Ingénieur**
1. Factulté (des) **STI**

**Comment by dalgetty** [comment]
I would go with 
Faculté STI

**Comment by ponsfrilus** [comment]
![image](https://user-images.githubusercontent.com/176002/37834713-a762d4c8-2eae-11e8-8984-9ab607d906dd.png)
