### ISSUE TITLE
The #redwave css bug

### ISSUE THREAD

**Issue by ponsfrilus** [epfl-sti/wordpress.theme#35]
The `#redwave` css element `min-width: 1400px;` is causing the horizontal scroll on mobile. This <https://gist.github.com/headquarters/5876199> script helps me to find it out, e.g. `Screen width is 320 and the following element is 1398`.

![image](https://user-images.githubusercontent.com/176002/34788753-d719d5b4-f63b-11e7-8830-20e997415343.png)

**Comment by domq** [comment]
Fixed at or around cd3cf83ddc91d804f266c56462386475dbe1e0e7, although I expect that one to reoccur every now and then
