### ISSUE TITLE
Common "cards" style for events, Professor pages, and more

### ISSUE THREAD

**Issue by domq** [epfl-sti/wordpress.theme#51]
One and the same theming should be applied to all pages that show details of an instance of some class or other.

It should have [Bootstrap cards](https://v4-alpha.getbootstrap.com/components/card/) of the following kinds:

- Most prominent, with red corners + special background (grey? To be validated)
- Less prominent, with same special background
- Least prominent, with plain white background
- Black background for misc info, goes to right bar (which is **not** a contextual nav menu even though it might have outgoing links e.g. Professor website), folds to the foot of page on mobile
- Free-style top right [mobile charge](https://en.wikipedia.org/wiki/Charge_(heraldry)) to put whatever, e.g. nice graphs out of some paper

Stretch goals:

- A superlatively prominent card showing a variation of Alex's "two huge bars on top and bottom" design, and with as-big-and-as-red-as-the-front-row-on-the-homepage typeface

**Comment by ponsfrilus** [comment]
```
Chers collègues, 
    comme vous le savez j'aimerais que nous essayions d'uniformiser les styles des pages contenant des listes de choses (ex : articles, thèmes, résultats d'une recherche texte) en nous appuyant sur les travaux en ce sens pour la page des profs.

Essentiellement, nous avons prévu des structures HTML avec des tags ad-hoc (documentées dans https://github.com/epfl-sti/wordpress.theme/blob/master/sass/theme/_cards.scss). Pour permettre aux «power users», tels que vous-même, d'éditer des pages ou posts comprenant ces tags, voici la marche à suivre :

 1. "puller" la branche master dans la vôtre à partir de maintenant (les
    changements nécessaires ont été introduits par
    https://github.com/epfl-sti/wordpress.theme/commit/1a06b2766260cc9fd1a24121e5d35d5a49c631e6)
 2. installer le plug-in "Toggle autowp"
    (https://wordpress.org/plugins/toggle-wpautop/)
 3. s'assurer de cocher Plugin → Disable autowp dans la page
    d'administration pour la page ou le post concerné (cf. pièce jointe)



Si vous oubliez les points 2 et 3, vous aurez des choses comme ceci dans vos «view source», ce qui est assez frustrant :

<p><card></p>

Merci de votre attention,
@domq
```
