### ISSUE TITLE
Common "list" page style for search results, video testimonials, newsletter archive, and more

### ISSUE THREAD

**Issue by domq** [epfl-sti/wordpress.theme#52]
Nice, stacked boxes showing a series of whatever, ticky-tacky, all the same.

Stretch goal: showing a series of whatever with intermediate subtitles, with a depth of just one (subtitles and entries). Five is right out

**Comment by ponsfrilus** [comment]
Fixed with the "List Page" template (See 250d01a5e4b9ffe4240a85dbd3ed74721f38b0d9).
