### ISSUE TITLE
The megamenu ought to be an actual menu

### ISSUE THREAD

**Issue by domq** [epfl-sti/wordpress.theme#54]
- People (with wp-admin access) shall be able to merrily drag'n-drop their way into changing *everything*
- It has to look just as nice as the old, page-of-&lt;ul&gt;s based one
- It must support adding all sorts of whacky widgets
- It should look nice on mobile, only slightly higher so you get a two-level effect with a little path running down the middle.

Stretch goal:
- It should be kept in sync automatically between French and English

**Comment by ponsfrilus** [comment]
https://wordpress.org/plugins/megamenu/ does the trick !
