### ISSUE TITLE
A personalized <topbar> background is to be made for every institute

### ISSUE THREAD

**Issue by domq** [epfl-sti/wordpress.theme#56]
N.B.: this is about drawing the banner backgrounds and validating them with the Institute directors;  *not* about [applying them automagically where necessary](https://github.com/epfl-sti/wordpress.theme/issues/55)

**Comment by ponsfrilus** [comment]
Done around [here](https://github.com/epfl-sti/wordpress.theme/blob/3b63cf92faa6d59cfc6885e6c21ee88f936387de/header.php#L19)
