### ISSUE TITLE
A story for access control (ACL)

### ISSUE THREAD

**Issue by domq** [epfl-sti/wordpress.theme#59]
- Based on Accred wherever possible (get access to that CADI API)
- EPFL-unit-level based just like Accred (looking at you, [Role Scoper](https://wordpress.org/plugins/role-scoper/)) i.e. subjects, objects and access relationships are tagged by one of the EPFL-defined scopes (lab/group/unit, institute/section/Centre, college/school/vice-presidence, and EPFL-wide)
- Still able to define ad-hoc permissions as needed (and scoped likewise)

**Comment by ponsfrilus** [comment]
From https://wordpress.stackexchange.com/questions/11268/wordpress-admins-or-roles-per-page
 * [ ] ~~https://wordpress.org/plugins/user-role-editor/~~ ([pro only](https://www.role-editor.com/allow-user-edit-selected-posts/))
 * [ ] ~~https://wordpress.org/plugins/press-permit-core/~~ ([pro only](https://presspermit.com/extensions/pp-collaborative-editing/))
 * [ ] ~~http://wordpress.org/extend/plugins/adminimize/~~ (hide unnecessary items in admin)
 * [x] http://wordpress.org/extend/plugins/role-scoper/ (Role Scoper **is no longer actively developed**, replaced by Press permit)
 * [ ] ~~https://wordpress.org/plugins/capability-manager-enhanced/~~ (roles only)
 * [ ] ~~https://wordpress.org/plugins/advanced-access-manager/~~ ([Plus Package](https://aamplugin.com/extension/plus-package))
 * [ ] ~~https://wordpress.org/plugins/restrict-content-by-role/~~ (roles only)
 * [x] https://wordpress.org/plugins/user-specific-content/

**Comment by ponsfrilus** [comment]
No ACL needed.
