### ISSUE TITLE
EPFL-STI-WordPress as a service

### ISSUE THREAD

**Issue by domq** [epfl-sti/wordpress.theme#71]
The Dean says: upon launching the site, we don't want to create a problem for ourselves if the Professors want to switch over to a similar layout

![Zing!](https://user-images.githubusercontent.com/1629585/35410759-b0375d7c-0216-11e8-9814-999bf494b22b.jpg)

**Comment by domq** [comment]
@domq

**Comment by ponsfrilus** [comment]
This is now a [milestone](https://github.com/epfl-sti/wordpress.theme/milestone/5)

**Comment by ponsfrilus** [comment]
Well, let's use the VPSI "unmanaged" service.
