### ISSUE TITLE
To Discuss: on a lab page, institute or school megamenu ?

### ISSUE THREAD

**Issue by ponsfrilus** [epfl-sti/wordpress.theme#81]
Need to discuss what mega menu is displayed on the labs' pages.

**Comment by alexwiderski** [comment]
School

Le ven. 9 févr. 2018 à 18:13, Nicolas Borboën <notifications@github.com> a
écrit :

**Comment by ponsfrilus** [comment]
For now, there are no lab page but only Prof/People page which have the school's menu,
