### ISSUE TITLE
Add the white news rows on institutes pages

### ISSUE THREAD

**Issue by ponsfrilus** [epfl-sti/wordpress.theme#87]

**Comment by domq** [comment]
Near as I can tell, this should Just Work™ with a new taxonomy and the proper setting in the widget

**Comment by ponsfrilus** [comment]
@domq it was't, the white news wasn't centered on an institute hompage... fixed by 1371e1e & af1c412 - it now uses a container and the row is centered with `justify-content-center align-items-center` bootstrap's classes.
